//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeyceryTradingCorporation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilePath
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilePath()
        {
            this.Products_Files = new HashSet<Products_Files>();
        }
    
        public int ID { get; set; }
        public string Path { get; set; }
        public string DateCreated { get; set; }
        public string DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Files> Products_Files { get; set; }
    }
}
